### ISSUE TITLE
Inventory tabs are rendered at wrong position when potion effect is active with NEI

### ISSUE THREAD

**Issue by Omgise** [makamys/Satchels#6]
https://user-images.githubusercontent.com/106000018/204134528-303a3caf-5f4f-42e9-8893-8a47183e0188.mp4

**Comment by Omgise** [comment]
I don't know what caused it

**Comment by makamys** [comment]
Can you post a mod list?

**Comment by Omgise** [comment]
> Can you post a mod list?

!MysteriumLib-1.1-deobf
[1.7.X]-拔刀剑附属似蛭-Nihil-r8
[残缺的al灬汉化-更多附魔]MoreEnchantments-1.7.10-1.3.2.1
[潘马斯农场]Pam's-Harvestcraft-1.7.10Lb-1.0.6-GTNH
[山樱]SlashBlade-Yamazakura-mc1.7-r4
00gasstation-mc1.7.10-0.4.0
adventurebackpack-1.7.10-1.0.5-GTNH
aether-1.7.10-v1.1.2.2
alreadydecoratingfix-1.0a
animfix-mc1.7.10-2.2.1
Anvilability-Forge-1.7.10-1.0.0
AppleCore-1.7.10-3.1.1
ATOP-1.7.10-v.1.2
Avaritia-1.7.10-1.31
backport5160-1.1m
Bamboo-2.6.8.5
bamboolight plus 1.0.0 MC1.7.10
baublelicious-1.7.10-1.2.2-final
BetterAchievements-1.7.10-0.1.0
BetterBurning-1.7.10-0.4.2
bettercrashes-1.7.10-1.1.7-GTNH
BiomesOPlenty-1.7.10-2.1.3-GTNH
BloodBlade1.3.9Final
Born+in+a+Barn+1.7.x
Botania-1.7.10-1.9.11-GTNH
BrandonsCore-1.7.10-1.0.0.13-GTNH
campfirebackport-1.7.10-1.10
Careful+Cast+Corrector-2.0
ChestTransporter-1.7.10-2.0.6
CodeChickenCore-1.7.10-1.1.6
CoFHCore-[1.7.10]3.1.4-329
CompatibilityLayerForCustomSkinLoader-ALPHA-11
CookingForBlockheads-1.7.10-1.2.13-GTNH
DarkRaven-mc1.7.2-r2
DefaultBOP-Forge-1.7.10-1.0.0
Draconic-Evolution-1.7.10-1.1.7-GTNH
Edible-Forge-1.7.10-1.0.0
ElephantFix-Forge-1.7.10-1.0.0
EnchantingPlus-1.7.10-3.0.2-d
endercore-1.7.10-0.2.11
EnderIO-1.7.10-2.3.1.48
endlessids-mc1.7.10-1.4.0-beta0003
Et_Futurum_Requiem-2.4.1-SNAPSHOT-89229f0
ExtraTiC-1.7.10-1.4.6
falsepatternlib-mc1.7.10-0.10.13
fastcraft-1.25
FastLeafDecay-1.7.10-1.4
FluorescentBar-mc1.7.2-r3
FoxExtra狐月刀改 v1.1.2(MC1710)
GodFox1.1.5Final
growthcraft-1.7.10-2.7.2-complete
HardcoreEnderExpansion-1.7.10-1.9.3-GTNH
IguanaTweaksTConstruct-1.7.10-2.2.3
industrialcraft-2-2.2.828-experimental
InputFix-1.7.10-v5
inventorytweaks-1.7.10-1.5.15
ironfurnaces-1.2.4R
KeepingInventory-1.7.10-2.1
Mantle-1.7.10-0.3.5
MaterialsPlus-1.7.10-1.2.0
Metallurgy-1.7.10-4.0.9.148
MetallurgyCore-1.7.10-4.0.5.30
ModernKeyBinding-Forge-1.7.10-2.1.0
modernsplash-1.7.10-2c17c9a
MurasamaBlade-mc1.7.2-r3.2
neodymium-1.7.10-0.1.5-11-ga7294e0
netherlicious-3.2.6
netherportalfix-mc1.7.10-1.1.1
NettyPatcher-0.2
Neutron-Forge-1.7.10-0.0.3
NoMoreRecipeConflict-1.7.10-0.3.2
NoSecrets-Forge-1.7.10-1.0.0
NotEnoughCharacters-1.7.10-1.4.8
NotEnoughItems-1.7.10-2.3.15-GTNH
NotEnoughPets-1.7.10-2.3.4
OptiFine-1.7.10_HD_U_E7
PlayerAPI-1.7.10-1.4
RenderPlayerAPI-1.7.10-1.4
SaltyMod+Expanded+[1.7.10]+[1.9.j]
Satchels-1.7.10-1.0.7
ServerPropertiesLAN-2.65-1.7.10
ShouldBeVanilla_1.7.10_1.20
SkinPort-1.7.10-v10d
SlashBlade_Zephyr-mc1.7.2-r1.2.2
Slashblade-AnvilEnchant-mc1.7.10-r1
SlashBlade-mc1.7.10-r88
SlashBladeWa-mc1.7.2-r1
SmartMoving-1.7.10-15.7-maka
SmartRender-1.7.10-2.1-1-g16592c9
SmithingInThe90'S-1.7.10-1.1.0
SoundFilters-0.8_for_1.7.X
SpecialMobs-1.7.10-3.3.13
squidless-1.7.10-0.6.1
SuperEnchants-0.5
TConstruct-1.7.10-1.9.7-GTNH
Thaumcraft-1.7.10-4.2.3.5
ThermalFoundation-[1.7.10]1.2.6-118
TiCTooltips-1.7.10-1.2.10
TofuCraft-2.1.8-mc1.7.10
torohealth-1.7.10-1.0.0
TRblade技术革新 v2.1.2[MC1.7.10]
TwilightForest-1.7.10-2.3.8.17
Uncrafted+1.7.10+(v.2.2.0)
VeinMiner-1.7.10-0.36.0.496+28a7f13
VillageNames-1.7.10-4.4.3
Waila-1.7.10-1.5.22
WailaHarvestability-1.7.10-1.1.10-GTNH
Wanderer-mc1.7.2-r1
WanionLib-1.7.10-1.8.3
Wawla-1.7.10-1.1.3-GTNH
Waystones_Jawsawn_Fork-mc1.7.10-1.0.0
weaponmod-v1.17.0
Baubles-1.7.10-1.0.1.14
CodeChickenLib-1.7.10-1.1.5.5

**Comment by Omgise** [comment]
Everything is normal when the potion is not used

https://user-images.githubusercontent.com/106000018/204192279-d4fc889f-9c21-4180-b678-20cd0f189bf4.mp4

**Comment by Omgise** [comment]
I think maybe the potion effect is causing the problem

**Comment by makamys** [comment]
Does it happens if you remove Satchels but keep everything else? It could be a bug in Tinkers' Construct's tab GUI (which Satchels also uses to render its tab).

**Comment by makamys** [comment]
Looks like we were both right. It happens if you've got a potion effect while using NEI (doesn't matter if it's the GTNH fork or the original) and mods that use TC's tab API (Satchels or TinkersConstruct). Interestingly, GalactiCraft's tab doesn't seem to have the issue.

**Comment by makamys** [comment]
It turns out [Hodgepodge](https://github.com/GTNewHorizons/Hodgepodge) has a patch that fixes this.

**Comment by Omgise** [comment]
> It turns out [Hodgepodge](https://github.com/GTNewHorizons/Hodgepodge) has a patch that fixes this.

But I CompatibilityLayerForCustomSkinLoader - ALPHA - 11 May need GasStation support, so may not be able to use a Hodgepodge

**Comment by makamys** [comment]
GTNHMixins + Mixingasm should work as a substitute for GasStation (at least in its current form).

**Comment by Omgise** [comment]
> GTNHMixins + Mixingasm should work as a substitute for GasStation (at least in its current form).

I'll try it out

**Comment by Omgise** [comment]
> GTNHMixins + Mixingasm should work as a substitute for GasStation (at least in its current form).

The game crashed
[fml-junk-earlystartup.log](https://github.com/makamys/Satchels/files/10103892/fml-junk-earlystartup.log)
[latest.log](https://github.com/makamys/Satchels/files/10103893/latest.log)
[fml-client-latest.log](https://github.com/makamys/Satchels/files/10103894/fml-client-latest.log)

**Comment by makamys** [comment]
Oh, GTNHMixins has an issue with mods that embed Mixin (such as Satchels). The fix is to rename the jar to come first alphabetically, e.g. `00gtnhmixins-2.1.1.jar`.

**Comment by Omgise** [comment]
> Oh, GTNHMixins has an issue with mods that embed Mixin (such as Satchels). The fix is to rename the jar to come first alphabetically, e.g. .`00gtnhmixins-2.1.1.jar`

The game is still crashing
[fml-client-latest.log](https://github.com/makamys/Satchels/files/10104691/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/makamys/Satchels/files/10104689/fml-junk-earlystartup.log)
[latest.log](https://github.com/makamys/Satchels/files/10104690/latest.log)

**Comment by Omgise** [comment]
I think there is a conflict with the industrialcraft mod. After deleting this mod, you can enter the game normally

**Comment by Omgise** [comment]
[crash-2022-11-28_22.58.30-client.txt](https://github.com/makamys/Satchels/files/10104866/crash-2022-11-28_22.58.30-client.txt)

**Comment by makamys** [comment]
Try disabling the ic2 stuff in Hodgepodge's config (every option that has `Ic2` in its name).

Actually disabling `fixIc2Hazmat` should be enough. The crash happens because the mixin that option enables references a GregTech class.

(Note from the future: the issue was fixed in Hodgepodge 2.0.10)

**Comment by Omgise** [comment]
Successfully entered the game, Thank makamys

**Comment by Omgise** [comment]
> Try disabling the ic2 stuff in Hodgepodge's config (every option that has `Ic2` in its name).
> 
> Actually disabling `fixIc2Hazmat` should be enough. The crash happens because the mixin that option enables references a GregTech class.

After running for a while, the game still crashes
[fml-junk-earlystartup.log](https://github.com/makamys/Satchels/files/10110160/fml-junk-earlystartup.log)
[latest.log](https://github.com/makamys/Satchels/files/10110161/latest.log)
[fml-client-latest.log](https://github.com/makamys/Satchels/files/10110162/fml-client-latest.log)

**Comment by Omgise** [comment]
[crash-2022-11-29_13.55.24-server.txt](https://github.com/makamys/Satchels/files/10110164/crash-2022-11-29_13.55.24-server.txt)

**Comment by makamys** [comment]
Aah, it's another GT5 assumption. Disable all the pollution stuff in the config (`railcraftPollutes`, `furnacesPollute`, `rocketsPollute`).
(Should be fixed now in Hodgepodge 2.0.9 actually.)

**Comment by Omgise** [comment]
> Aah, it's another GT5 assumption. Disable all the pollution stuff in the config (`railcraftPollutes`, `furnacesPollute`, `rocketsPollute`). (Should be fixed now in Hodgepodge 2.0.9 actually.)

Now the problem is solved, thank you :D

**Comment by makamys** [comment]
Gonna close this then, if Hodgepodge's fix works I'd rather not add needless hacks to fix the issue from my side.
